### PR TITLE
Update streamutils.py

### PR DESCRIPTION
**Pull request by bdherouville**
Fixed indentation issues

### CODE REVIEW

**Comment by dataplayer12** [comment]
Hi, thank you for the PR. Have you faced any problems in using the code due to indentation issues? I am wondering if other users had been facing these issues all this while.

**Comment by bdherouville** [comment]
Hi,

Yes, I tried to run it on my TX2 and got this error.
Now it is ok.

Kind regards,

Le mar. 28 juil. 2020 à 11:33, Jaiyam Sharma <notifications@github.com> a
écrit :

**Comment by dataplayer12** [comment]
I checked and I got the same problem, so I will merge this commit. Merci beaucoup

**Comment by bdherouville** [comment]
You're welcome !

Stay safe ! Where do you live ? Just for curiosity.

Le mar. 28 juil. 2020 à 11:42, Jaiyam Sharma <notifications@github.com> a
écrit :

**Comment by dataplayer12** [comment]
I live in a small town in Japan. I went to Nantes for a semester in my Bachelor's, so I can speak a bit of French.

**Comment by bdherouville** [comment]
That's great ! Thank you !
Keep in touch, I sent you a Linkedin invitation.

Kind regards,

Bertrand

Le mar. 28 juil. 2020 à 11:49, Jaiyam Sharma <notifications@github.com> a
écrit :

**Pull request merged**
